server:
  port: 0  # random test port

spring:
  application:
    name: employee-management-service-test

  datasource:
    url: jdbc:postgresql://localhost:5432/employee_db
    username: postgres
    password: passpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  main:
    allow-bean-definition-overriding: true

jwt:
  secret: 3b8b6f6a2c4a8f0b90e2c7c9f67f8e8a1d1a2b3c4d5e6f708091a1b2c3d4e5f6
  expiration: 86400000

eureka:
  client:
    enabled: false  # no Eureka during tests
  instance:
    prefer-ip-address: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
