server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: employee-service
          uri: lb://employee-management-service
          predicates:
            - Path=/employee/**
          filters:
            - StripPrefix=1
        # Swagger proxy routes...
        - id: auth-swagger
          uri: lb://auth-service
          predicates:
            - Path=/auth/v3/api-docs/**
          filters:
            - RewritePath=/auth/(?<path>.*), /$\{path}
        # ... rest of your routes
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      global-cors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-methods: "*"
            allowed-headers: "*"
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

jwt:
  secret: ${JWT_SECRET:3b8b6f6a2c4a8f0b90e2c7c9f67f8e8a1d1a2b3c4d5e6f708091a1b2c3d4e5f6}
  expiration: ${JWT_EXPIRATION:86400000}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth Service
        url: /auth/v3/api-docs
      - name: Employee Management Service
        url: /employee/v3/api-docs

logging:
  level:
    org.springdoc: DEBUG
    org.springframework.cloud.gateway: DEBUG